### ISSUE TITLE
dx8

### ISSUE THREAD

**Issue by Karaulov** [hrydgard/minidx9#1]
Why minidx9 does not contain minidx8 SDK? :(

**Comment by hrydgard** [comment]
I set it up with the stuff I needed. Why don't you set up a minidx8 yourself?

**Comment by hrydgard** [comment]
I set it up with the stuff I needed, and I didn't need DX8. Set one up
yourself :)

2016-11-28 11:53 GMT+01:00 Karaulov <notifications@github.com>:

**Comment by Karaulov** [comment]
"Why don't you set up a minidx8 yourself?"
Why you set up a minidx9 yourself? 

dx8 used in many old games)
